services:
  - type: web
    name: drf-app
    env: python
    buildCommand: >
      pip install -r requirements.txt &&
      playwright install --with-deps &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
